[build]
publish = "playground/dist"
command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[build.environment]
NPM_FLAGS = "--prefix=/dev/null"
NODE_VERSION = "14"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
