import DefaultColors from './default.json'

export const Themes = {
  Default: DefaultColors,
  VitesseLight: {
    '--prism-scheme': 'light',
    '--prism-foreground': '#393a34',
    '--prism-background': '#f8f8f8',
    '--prism-comment': '#b8c4b8',
    '--prism-namespace': '#c96880',
    '--prism-string': '#ad7863',
    '--prism-punctuation': '#8e8f8b',
    '--prism-literal': '#36acaa',
    '--prism-keyword': '#248459',
    '--prism-function': '#849145',
    '--prism-deleted': '#9a050f',
    '--prism-class': '#2b91af',
    '--prism-builtin': '#800000',
    '--prism-property': '#ad502b',
  },
  VitesseDark: {
    '--prism-scheme': 'dark',
    '--prism-foreground': '#d4d4d4',
    '--prism-background': '#1e1e1e',
    '--prism-comment': '#758575',
    '--prism-namespace': '#c96880',
    '--prism-string': '#ce9178',
    '--prism-punctuation': '#d4d4d4',
    '--prism-literal': '#36acaa',
    '--prism-keyword': '#38a776',
    '--prism-function': '#dcdcaa',
    '--prism-deleted': '#9a050f',
    '--prism-class': '#4ec9b0',
    '--prism-builtin': '#d16969',
    '--prism-property': '#ce9178',
    '--prism-regex': '#ad502b',
    '--prism-line-number': '#888888',
    '--prism-line-number-gutter': '#eeeeee',
    '--prism-line-highlight-background': '#444444',
    '--prism-selection-background': '#444444',
  },
}
