// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonDocumentDownload: typeof import('~icons/carbon/document-download')['default']
    CarbonDownload: typeof import('~icons/carbon/download')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    VarItem: typeof import('./src/components/VarItem.vue')['default']
  }
}

export {}
