/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    VarItem: typeof import('./src/components/VarItem.vue')['default']
  }
}
